/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysSaleOrganization;

import Business.Organization.SysSaleOrganization;
import UserInterface.SystemAdmin.*;
import Business.Organization.SystemAdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.System.AmazonSystem;

/**
 *
 * @author hyf
 */
public class SysSaleRoleWorkareaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkareaJPanel
     */
    JPanel userProcessContainer;
    AmazonSystem system;
    SysSaleOrganization organization;
    UserAccount account;

    public SysSaleRoleWorkareaJPanel(JPanel userProcessContainer, UserAccount account, SysSaleOrganization organization, AmazonSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageNetworkJButton = new javax.swing.JButton();
        manageNetworkJButton1 = new javax.swing.JButton();
        manageNetworkJButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        manageNetworkJButton.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton.setText("Manage order");
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });

        manageNetworkJButton1.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton1.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton1.setText("view supplier rate");
        manageNetworkJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton1ActionPerformed(evt);
            }
        });

        manageNetworkJButton2.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton2.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton2.setText("view product rate");
        manageNetworkJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageNetworkJButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(manageNetworkJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(manageNetworkJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageNetworkJButton)
                    .addComponent(manageNetworkJButton1))
                .addGap(39, 39, 39)
                .addComponent(manageNetworkJButton2)
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed

        ManageOrderJPanel mojp = new ManageOrderJPanel(userProcessContainer, account, organization, system);
        userProcessContainer.add("manageEmployeeJPanel", mojp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void manageNetworkJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton1ActionPerformed
        // TODO add your handling code here:
        ViewSupplierRateJPanel mojp = new ViewSupplierRateJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEmployeeJPanel", mojp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButton1ActionPerformed

    private void manageNetworkJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton2ActionPerformed
        // TODO add your handling code here:
        ViewProductRateJPanel mojp = new ViewProductRateJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEmployeeJPanel", mojp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JButton manageNetworkJButton1;
    private javax.swing.JButton manageNetworkJButton2;
    // End of variables declaration//GEN-END:variables
}
