/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysSaleOrganization;

import UserInterface.Customer.*;
import UserInterface.ShipOrganization.*;
import UserInterface.Customer.*;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Supplier;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Order.ShippingAndTax;
import Business.Organization.Organization;
import Business.Organization.SysWarehouseOrganization;
import Business.Organization.SystemAdminOrganization;
import Business.Organization.WarehouseOrganization;
import Business.Product.Product;
import Business.Product.ProductDirectory;
import Business.Product.ProductSubDirectory;
import Business.System.AmazonSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author hyf
 */
public class ViewSupplierRateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookOrderJPanel
     */
    JPanel userProcessContainer;
    AmazonSystem system;
    Order order;
    UserAccount user;

    public ViewSupplierRateJPanel(JPanel userProcessContainer,AmazonSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.order = order;
        this.system = system;
        this.user = user;
        popTree();
    }

    public void poputaleSupplierTable(Network network) {
        int rowCount = productJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) productJTable.getModel()).removeRow(i);
        }
        for (Enterprise e : network.getEnterpriseList()) {
            if (e instanceof Supplier) {
                if (((Supplier) e).getReviews() != null) {
                    Object row[] = new Object[4];
                    row[0] = (Supplier) e;
                    row[1] = ((Supplier) e).getLocation();
                    row[2] = ((Supplier) e).rate();
                    row[3] = ((Supplier) e).getFlag();
                    ((DefaultTableModel) productJTable.getModel()).addRow(row);
                }
            }

        }

    }

    private void popTree() {
        DefaultTreeModel model = (DefaultTreeModel) productCatalogJTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        DefaultMutableTreeNode Networks = new DefaultMutableTreeNode("Networks");
        root.insert(Networks, 0);
        ArrayList<ProductDirectory> directorys = null;
        for (int i = 0; i < system.getNetworklist().size(); i++) {
            Network n = system.getNetworklist().get(i);
            DefaultMutableTreeNode Networknode = new DefaultMutableTreeNode(n);
            Networks.insert(Networknode, i);
            for (int j = 0; j < n.getEnterpriseList().size(); j++) {
                Enterprise enterprise = n.getEnterpriseList().get(j);
                DefaultMutableTreeNode enterprisenode = new DefaultMutableTreeNode(enterprise);
                Networknode.insert(enterprisenode, j);
                model.reload();
            }
            productCatalogJTree.getSelectionModel().setSelectionMode(
                    TreeSelectionModel.SINGLE_TREE_SELECTION);
            productCatalogJTree.addTreeSelectionListener(new TreeSelectionListener() {
                @Override
                public void valueChanged(TreeSelectionEvent tse) {
                    DefaultMutableTreeNode node = (DefaultMutableTreeNode) productCatalogJTree.getLastSelectedPathComponent();
                    if (node == null) {
                        return;
                    }
                    Object nodeinfo = node.getUserObject();
                    if (nodeinfo instanceof Network) {
                        poputaleSupplierTable((Network) nodeinfo);
                    }
                }
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productJTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        productCatalogJTree = new javax.swing.JTree();
        backjButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rateJTextField1 = new javax.swing.JTextField();
        viewProdjButton3 = new javax.swing.JButton();
        viewProdjButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        productJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier", "Location", "Rate", "Flag"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productJTable);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("system");
        productCatalogJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        productCatalogJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                productCatalogJTreeValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(productCatalogJTree);

        backjButton3.setBackground(new java.awt.Color(0, 153, 0));
        backjButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backjButton3.setForeground(new java.awt.Color(255, 255, 255));
        backjButton3.setText("<< Back");
        backjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("profit");

        viewProdjButton3.setBackground(new java.awt.Color(255, 51, 0));
        viewProdjButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        viewProdjButton3.setForeground(new java.awt.Color(255, 255, 255));
        viewProdjButton3.setText("change profit");
        viewProdjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProdjButton3ActionPerformed(evt);
            }
        });

        viewProdjButton4.setBackground(new java.awt.Color(0, 102, 255));
        viewProdjButton4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        viewProdjButton4.setForeground(new java.awt.Color(255, 255, 255));
        viewProdjButton4.setText("view profit");
        viewProdjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProdjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton3)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rateJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(viewProdjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(viewProdjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(rateJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewProdjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewProdjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(244, 244, 244)))
                .addComponent(backjButton3)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productCatalogJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_productCatalogJTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectNode = (DefaultMutableTreeNode) productCatalogJTree.getLastSelectedPathComponent();
    }//GEN-LAST:event_productCatalogJTreeValueChanged

    private void backjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton3ActionPerformed

    private void viewProdjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProdjButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = productJTable.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Supplier o = (Supplier) productJTable.getValueAt(selectedRow, 0);
        o.setProfit(Float.valueOf(rateJTextField1.getText()));
    }//GEN-LAST:event_viewProdjButton3ActionPerformed

    private void viewProdjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProdjButton4ActionPerformed
        // TODO add your handling code here:
         int selectedRow = productJTable.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Supplier o = (Supplier) productJTable.getValueAt(selectedRow, 0);
        rateJTextField1.setText(String.valueOf(o.getProfit()));
    }//GEN-LAST:event_viewProdjButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree productCatalogJTree;
    private javax.swing.JTable productJTable;
    private javax.swing.JTextField rateJTextField1;
    private javax.swing.JButton viewProdjButton3;
    private javax.swing.JButton viewProdjButton4;
    // End of variables declaration//GEN-END:variables
}
