/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseOrganization;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Supplier;
import Business.Organization.Organization;
import Business.Organization.SysWarehouseOrganization;
import Business.Organization.WarehouseOrganization;
import Business.Product.Product;
import Business.Product.ProductDirectory;
import Business.Product.ProductDirectory.DType;
import Business.Product.ProductSubDirectory;
import Business.Product.ProductSubDirectory.PType;
import Business.System.AmazonSystem;
import java.awt.CardLayout;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author hyf
 */
public class CreateProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateProductJPanel
     */
    JPanel userProcessContainer;
    WarehouseOrganization organization;
    Enterprise enterprise;
    AmazonSystem system;
    DType dType;
    PType pType;
    Product product;
    ProductSubDirectory sysSubDirectory;
    ProductDirectory sysDirectory;
    ProductSubDirectory subDirectory;
    ProductDirectory directory;

    public CreateProductJPanel(JPanel userProcessContainer, WarehouseOrganization organization, Enterprise enterprise, AmazonSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        product = new Product();
        typeComboBox1.removeAllItems();
        for (DType d : ProductDirectory.DType.values()) {
            typeComboBox1.addItem(d);
        }
        ptypeComboBox2.removeAllItems();
        for (PType p : ProductSubDirectory.PType.values()) {
            ptypeComboBox2.addItem(p);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        priceJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        availabilityJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addProductJButton1 = new javax.swing.JButton();
        typeComboBox1 = new javax.swing.JComboBox();
        ptypeComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        idJLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backjButton3 = new javax.swing.JButton();

        jLabel3.setText("availablity");

        jLabel1.setText("price");

        jLabel2.setText("name");

        addProductJButton1.setBackground(new java.awt.Color(255, 51, 0));
        addProductJButton1.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        addProductJButton1.setForeground(new java.awt.Color(255, 255, 255));
        addProductJButton1.setText("add");
        addProductJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductJButton1ActionPerformed(evt);
            }
        });

        typeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBox1ActionPerformed(evt);
            }
        });

        ptypeComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptypeComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("picture");

        jButton7.setBackground(new java.awt.Color(0, 102, 255));
        jButton7.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Choose Picture");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel6.setText("id");

        backjButton3.setBackground(new java.awt.Color(0, 153, 0));
        backjButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backjButton3.setForeground(new java.awt.Color(255, 255, 255));
        backjButton3.setText("<< Back");
        backjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availabilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idJLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addProductJButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(ptypeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton3)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptypeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(availabilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idJLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(50, 50, 50)
                .addComponent(addProductJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(backjButton3)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addProductJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductJButton1ActionPerformed
        // TODO add your handling code here: 
        for (ProductDirectory d : organization.getProductCatalog().getProductDirectorys()) {
            if (d.getDtype() == dType) {
                directory = d;
                for (ProductSubDirectory s : directory.getSubDirectoryList()) {
                    if (s.getPtype() == pType) {
                        subDirectory = s;
                        break;
                    }
                }
                if (subDirectory == null) {
                    subDirectory = directory.newSubDirectory(pType);
                }

            }
        }
        if (directory == null) {
            directory = organization.getProductCatalog().create(dType);
            subDirectory = directory.newSubDirectory(pType);
        }

        /*     for (ProductDirectory directory : ((Supplier)enterprise).getProductCatalog().getProductDirectorys()) {
         if (directory.getDtype() == dType) {
         for (ProductSubDirectory subDirectory : directory.getSubDirectoryList()) {
         if (subDirectory.getPtype() == pType) {
         product = subDirectory.newProduct();
         product.setName(nameJTextField.getText());
         product.setPrice(Integer.parseInt(priceJTextField.getText()));
         product.setAvailable(Integer.parseInt(availabilityJTextField.getText()));
         }
         }

         }
         }*/
        /*  for (Organization o : system.getOrganizationDirectory().getOrganizationList()) {
         if (o instanceof SysWarehouseOrganization) {
         for (ProductDirectory directory : ((SysWarehouseOrganization) o).getProductCatalog().getProductDirectorys()) {
         if (directory.getDtype() == dType) {
         for (ProductSubDirectory subDirectory : directory.getSubDirectoryList()) {
         if (subDirectory.getPtype() == pType) {
         product = subDirectory.newProduct();
         product.setName(nameJTextField.getText());
         product.setPrice(Integer.parseInt(priceJTextField.getText()));
         product.setAvailable(Integer.parseInt(availabilityJTextField.getText()));

         }
         }

         }

         }
         }
         }*/
        for (Organization o : system.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof SysWarehouseOrganization) {
                for (ProductDirectory d : ((SysWarehouseOrganization) o).getProductCatalog().getProductDirectorys()) {
                    if (d.getDtype() == dType) {
                        sysDirectory = d;
                        for (ProductSubDirectory s : sysDirectory.getSubDirectoryList()) {
                            if (s.getPtype() == pType) {
                                sysSubDirectory = s;
                                break;
                            }
                        }
                        if (sysSubDirectory == null) {
                            sysSubDirectory = sysDirectory.newSubDirectory(pType);
                        }
                    }
                }
            }
        }
        if (sysDirectory == null) {
            sysDirectory = organization.getProductCatalog().create(dType);
            sysSubDirectory = sysDirectory.newSubDirectory(pType);
        }
        product.setName(nameJTextField.getText());
        product.setPrice(Integer.parseInt(priceJTextField.getText()));
        product.setAvailable(Integer.parseInt(availabilityJTextField.getText()));
        subDirectory.newProduct(product);
        sysSubDirectory.newProduct(product);
        idJLabel5.setText(String.valueOf(product.getProductId()));
    }//GEN-LAST:event_addProductJButton1ActionPerformed

    private void typeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBox1ActionPerformed

        dType = (DType) typeComboBox1.getSelectedItem();
    }//GEN-LAST:event_typeComboBox1ActionPerformed

    private void ptypeComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptypeComboBox2ActionPerformed
        // TODO add your handling code here:
        pType = (PType) ptypeComboBox2.getSelectedItem();
    }//GEN-LAST:event_ptypeComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        String s = chooser.getSelectedFile().getAbsolutePath();
        product.setPicture(s);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void backjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductJButton1;
    private javax.swing.JTextField availabilityJTextField;
    private javax.swing.JButton backjButton3;
    private javax.swing.JLabel idJLabel5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JComboBox ptypeComboBox2;
    private javax.swing.JComboBox typeComboBox1;
    // End of variables declaration//GEN-END:variables
}
