/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseOrganization;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Supplier;
import Business.Organization.Organization;
import Business.Organization.SysWarehouseOrganization;
import Business.Organization.WarehouseOrganization;
import Business.Product.Product;
import Business.Product.ProductDirectory;
import Business.Product.ProductDirectory.DType;
import Business.Product.ProductSubDirectory;
import Business.Product.ProductSubDirectory.PType;
import Business.System.AmazonSystem;
import java.awt.CardLayout;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author hyf
 */
public class CreateExistProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateProductJPanel
     */
    JPanel userProcessContainer;
    WarehouseOrganization organization;
    Enterprise enterprise;
    AmazonSystem system;
    DType dType;
    PType pType;
    Product product;

    public CreateExistProductJPanel(JPanel userProcessContainer, WarehouseOrganization organization, Enterprise enterprise, AmazonSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        typeComboBox1.removeAllItems();
        for (DType d : ProductDirectory.DType.values()) {
            typeComboBox1.addItem(d);
        }
        ptypeComboBox2.removeAllItems();
        for (PType p : ProductSubDirectory.PType.values()) {
            ptypeComboBox2.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availabilityJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addProductJButton1 = new javax.swing.JButton();
        typeComboBox1 = new javax.swing.JComboBox();
        ptypeComboBox2 = new javax.swing.JComboBox();
        idJTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idJTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        backjButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("quantity");

        addProductJButton1.setBackground(new java.awt.Color(255, 51, 0));
        addProductJButton1.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        addProductJButton1.setForeground(new java.awt.Color(255, 255, 255));
        addProductJButton1.setText("add");
        addProductJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductJButton1ActionPerformed(evt);
            }
        });

        typeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBox1ActionPerformed(evt);
            }
        });

        ptypeComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptypeComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Product ID");

        jLabel6.setText("ID");

        backjButton3.setBackground(new java.awt.Color(0, 153, 0));
        backjButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backjButton3.setForeground(new java.awt.Color(255, 255, 255));
        backjButton3.setText("<< Back");
        backjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProductJButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(ptypeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(availabilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(264, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton3)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptypeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(availabilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(addProductJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(backjButton3)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addProductJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductJButton1ActionPerformed
        // TODO add your handling code here: 
        for (ProductDirectory directory : organization.getProductCatalog().getProductDirectorys()) {
            if (directory.getDtype() == dType) {
                for (ProductSubDirectory subDirectory : directory.getSubDirectoryList()) {
                    if (subDirectory.getPtype() == pType) {
                        product = subDirectory.findItem(Integer.parseInt(idJTextField1.getText()));
                        product.setId(Integer.parseInt(idJTextField2.getText()));
                        product.setAvailable(Integer.parseInt(availabilityJTextField.getText()) + product.getAvailable());
                    }
                }
            }
        }

        /*   for (Organization o : system.getOrganizationDirectory().getOrganizationList()) {
         if (o instanceof SysWarehouseOrganization) {
         for (ProductDirectory directory : ((SysWarehouseOrganization) o).getProductCatalog().getProductDirectorys()) {
         if (directory.getDtype() == dType) {
         for (ProductSubDirectory subDirectory : directory.getSubDirectoryList()) {
         if (subDirectory.getPtype() == pType) {
         product = subDirectory.findItem(Integer.parseInt(idJTextField1.getText()));
         product.setAvailable(Integer.parseInt(availabilityJTextField.getText()) + product.getAvailable());
         }
         }

         }

         }
         }
         }*/
    }//GEN-LAST:event_addProductJButton1ActionPerformed

    private void typeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBox1ActionPerformed

        dType = (DType) typeComboBox1.getSelectedItem();
    }//GEN-LAST:event_typeComboBox1ActionPerformed

    private void ptypeComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptypeComboBox2ActionPerformed
        // TODO add your handling code here:
        pType = (PType) ptypeComboBox2.getSelectedItem();
    }//GEN-LAST:event_ptypeComboBox2ActionPerformed

    private void backjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductJButton1;
    private javax.swing.JTextField availabilityJTextField;
    private javax.swing.JButton backjButton3;
    private javax.swing.JTextField idJTextField1;
    private javax.swing.JTextField idJTextField2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox ptypeComboBox2;
    private javax.swing.JComboBox typeComboBox1;
    // End of variables declaration//GEN-END:variables
}
