/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.System.AmazonSystem;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hyf
 */
public class CustomerWorkareaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkareaJPanel
     */
    JPanel userProcessContainer;
    UserAccount user;
    AmazonSystem system;
    Network network;

    public CustomerWorkareaJPanel(JPanel userProcessContainer, UserAccount user, AmazonSystem system) {
        initComponents();
        this.user = user;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        networkComboBox1.removeAllItems();
        for (Network network : system.getNetworklist()) {
            networkComboBox1.addItem(network);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyJButton = new javax.swing.JButton();
        reportJButton = new javax.swing.JButton();
        networkComboBox1 = new javax.swing.JComboBox();
        normalServeJButton1 = new javax.swing.JButton();
        historyJButton1 = new javax.swing.JButton();
        reportJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        historyJButton.setBackground(new java.awt.Color(255, 51, 0));
        historyJButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        historyJButton.setForeground(new java.awt.Color(255, 255, 255));
        historyJButton.setText("view order history");
        historyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyJButtonActionPerformed(evt);
            }
        });

        reportJButton.setBackground(new java.awt.Color(255, 51, 0));
        reportJButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        reportJButton.setForeground(new java.awt.Color(255, 255, 255));
        reportJButton.setText("manage finance accounts");
        reportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJButtonActionPerformed(evt);
            }
        });

        networkComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBox1ActionPerformed(evt);
            }
        });

        normalServeJButton1.setBackground(new java.awt.Color(255, 51, 0));
        normalServeJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        normalServeJButton1.setForeground(new java.awt.Color(255, 255, 255));
        normalServeJButton1.setText("Shopping");
        normalServeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalServeJButton1ActionPerformed(evt);
            }
        });

        historyJButton1.setBackground(new java.awt.Color(255, 51, 0));
        historyJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        historyJButton1.setForeground(new java.awt.Color(255, 255, 255));
        historyJButton1.setText("view request");
        historyJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyJButton1ActionPerformed(evt);
            }
        });

        reportJButton1.setBackground(new java.awt.Color(255, 51, 0));
        reportJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        reportJButton1.setForeground(new java.awt.Color(255, 255, 255));
        reportJButton1.setText("instalment");
        reportJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(networkComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(normalServeJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(historyJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reportJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(historyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(networkComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historyJButton)
                    .addComponent(normalServeJButton1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historyJButton1)
                    .addComponent(reportJButton))
                .addGap(48, 48, 48)
                .addComponent(reportJButton1)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJButtonActionPerformed
        // TODO add your handling code here:
        manageFinanceJPanel fjp = new manageFinanceJPanel(userProcessContainer, user);
        userProcessContainer.add("6", fjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportJButtonActionPerformed

    private void networkComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBox1ActionPerformed

        network = (Network) networkComboBox1.getSelectedItem();
    }//GEN-LAST:event_networkComboBox1ActionPerformed

    private void historyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyJButtonActionPerformed
        // TODO add your handling code here:
        OrderHistoryJPanel ohj = new OrderHistoryJPanel(userProcessContainer, user, system);

        userProcessContainer.add("7", ohj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_historyJButtonActionPerformed

    private void normalServeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalServeJButton1ActionPerformed
        // TODO add your handling code here:
        NormalBookOrderJPanel bojp = new NormalBookOrderJPanel(userProcessContainer, user, system, network);
        userProcessContainer.add("8", bojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        /*BookOrderJPanel bojp = new BookOrderJPanel(userProcessContainer,user,system,network);
         userProcessContainer.add("ManageSuppliersJPanel", bojp);
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);*/
    }//GEN-LAST:event_normalServeJButton1ActionPerformed

    private void historyJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyJButton1ActionPerformed
        // TODO add your handling code here:
        TotalRequestJPanel rjp = new TotalRequestJPanel(userProcessContainer, user, system);
        userProcessContainer.add("9", rjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_historyJButton1ActionPerformed

    private void reportJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJButton1ActionPerformed
        // TODO add your handling code here:
        InstalmentPayJPanel ipjp = new InstalmentPayJPanel(userProcessContainer, user, system);
        userProcessContainer.add("10", ipjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportJButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton historyJButton;
    private javax.swing.JButton historyJButton1;
    private javax.swing.JComboBox networkComboBox1;
    private javax.swing.JButton normalServeJButton1;
    private javax.swing.JButton reportJButton;
    private javax.swing.JButton reportJButton1;
    // End of variables declaration//GEN-END:variables
}
