/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.FinanceAccount.FinanceAccount;
import Business.FinanceAccount.TrasactionAccount;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.AccountingOrganization;
import Business.Organization.SysFinanceOrganization;
import Business.Organization.Organization;
import Business.Organization.ShipOrganization;
import Business.Payment.Payment;
import Business.Shipment.Shipment;
import Business.System.AmazonSystem;
import Business.UserAccount.UserAccount;
import Business.UserAddress.ShippingAddress;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author hyf
 */
public class instalmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShippingJPanel
     */
    JPanel userProcessContainer;
    Order order;
    AmazonSystem system;
    ShippingAddress shippingAddress;
    UserAccount user;
    int length;
    public instalmentJPanel(JPanel userProcessContainer, Order order,UserAccount user, AmazonSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.order = order;
        this.system = system;
        this.user = user;
        lengthJComboBox.removeAllItems();
        System.out.println(order.getCustomer().getUsername());
        for (int i = 1; i < 13; i++) {
            lengthJComboBox.addItem(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lengthJComboBox = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        checkoutJButton1 = new javax.swing.JButton();
        backjButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lengthJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lengthJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthJComboBoxActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 0));
        jLabel18.setText("Choose number of month to pay");

        checkoutJButton1.setBackground(new java.awt.Color(0, 153, 0));
        checkoutJButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        checkoutJButton1.setForeground(new java.awt.Color(255, 255, 255));
        checkoutJButton1.setText(" submit >>");
        checkoutJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutJButton1ActionPerformed(evt);
            }
        });

        backjButton2.setBackground(new java.awt.Color(0, 153, 0));
        backjButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        backjButton2.setForeground(new java.awt.Color(255, 255, 255));
        backjButton2.setText("<< back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(lengthJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(815, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(checkoutJButton1)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addComponent(lengthJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 972, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutJButton1)
                    .addComponent(backjButton2))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lengthJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthJComboBoxActionPerformed
        // TODO add your handling code here:
        String l = (String) lengthJComboBox.getSelectedItem();
        if(l==null){
            return;
        }
        length=Integer.parseInt(l);
        order.getPayment().setLength(length);
        order.getPayment().setTotal(order.totalMoney()/length);
    }//GEN-LAST:event_lengthJComboBoxActionPerformed

    private void checkoutJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutJButton1ActionPerformed
        // TODO add your handling code here:
        InvoiceJPanel ijp = new InvoiceJPanel(userProcessContainer, order, user, system);
        userProcessContainer.add("ViewProductDetailJPanel", ijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_checkoutJButton1ActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JButton checkoutJButton1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JComboBox lengthJComboBox;
    // End of variables declaration//GEN-END:variables
}
