/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Supplier;
import Business.Invoice.Invoice;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Order.ShippingAndTax;
import Business.Organization.Organization;
import Business.Organization.SystemAdminOrganization;
import Business.Organization.WarehouseOrganization;
import Business.Product.Product;
import Business.System.AmazonSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hyf
 */
public class InstalmentPayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookOrderJPanel
     */
    JPanel userProcessContainer;
    AmazonSystem system;
    UserAccount user;
    Invoice invoice;

    public InstalmentPayJPanel(JPanel userProcessContainer, UserAccount user, AmazonSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
        popOrderTable();

    }

    public void popOrderTable() {
        int rowCount = orderhistoryJTable1.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) orderhistoryJTable1.getModel()).removeRow(i);
        }
        for (Order o : user.getOrderHistory().getOrders()) {
            if (!o.getInvoice().finish()) {
                Object row[] = new Object[7];
                row[0] = o;
                row[1] = o.getSubtotalPrice();
                row[2] = o.tax();
                row[3] = o.shipping();
                row[4] = o.totalMoney();
                row[5] = o.getOrderDate();
                row[6] = o.getShipment().getStatus();
                ((DefaultTableModel) orderhistoryJTable1.getModel()).addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderhistoryJTable1 = new javax.swing.JTable();
        receiveJButton1 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        orderhistoryJTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderhistoryJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order number", "subtotal", "tax", "shipping fee", "Order total", "Order time", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderhistoryJTable1);

        receiveJButton1.setBackground(new java.awt.Color(0, 153, 0));
        receiveJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        receiveJButton1.setForeground(new java.awt.Color(255, 255, 255));
        receiveJButton1.setText("pay");
        receiveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveJButton1ActionPerformed(evt);
            }
        });

        backjButton1.setBackground(new java.awt.Color(0, 153, 0));
        backjButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(255, 255, 255));
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(receiveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiveJButton1)
                    .addComponent(backjButton1))
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void receiveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderhistoryJTable1.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Order order = (Order) orderhistoryJTable1.getValueAt(selectedRow, 0);
        invoice = order.getInvoice();
        invoice.setPaid(order.getPayment().getTotal()*invoice.Pay());
        invoice.setUnpaid(order.totalMoney() - invoice.getPaid());
        InvoiceAfterJPanel ijp = new InvoiceAfterJPanel(userProcessContainer, order, user, system);
        userProcessContainer.add("3", ijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_receiveJButton1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderhistoryJTable1;
    private javax.swing.JButton receiveJButton1;
    // End of variables declaration//GEN-END:variables
}
