/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.FinanceAccount.FinanceAccount;
import Business.FinanceAccount.TrasactionAccount;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.AccountingOrganization;
import Business.Organization.SysFinanceOrganization;
import Business.Organization.Organization;
import Business.Organization.ShipOrganization;
import Business.Payment.Payment;
import Business.Product.Product;
import Business.Product.Review;
import Business.System.AmazonSystem;
import Business.UserAccount.UserAccount;
import Business.UserAddress.BillAddress;
import Business.UserAddress.ShippingAddress;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hyf
 */
public class TotalRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BillingJPanel
     */
    JPanel userProcessContainer;
    AmazonSystem system;
    UserAccount user;
    Product product;

    public TotalRequestJPanel(JPanel userProcessContainer,UserAccount user, AmazonSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        complaintJButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        manageEnterpriseJButton1 = new javax.swing.JButton();
        manageEnterpriseJButton3 = new javax.swing.JButton();
        manageEnterpriseJButton5 = new javax.swing.JButton();
        returnJButton1 = new javax.swing.JButton();
        manageEnterpriseJButton2 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        complaintJButton2.setBackground(new java.awt.Color(255, 51, 0));
        complaintJButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        complaintJButton2.setForeground(new java.awt.Color(255, 255, 255));
        complaintJButton2.setText("complaint");
        complaintJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintJButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Supplier request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        manageEnterpriseJButton1.setBackground(new java.awt.Color(255, 51, 0));
        manageEnterpriseJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageEnterpriseJButton1.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton1.setText("return before Request");
        manageEnterpriseJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButton1ActionPerformed(evt);
            }
        });

        manageEnterpriseJButton3.setBackground(new java.awt.Color(255, 51, 0));
        manageEnterpriseJButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageEnterpriseJButton3.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton3.setText("change");
        manageEnterpriseJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButton3ActionPerformed(evt);
            }
        });

        manageEnterpriseJButton5.setBackground(new java.awt.Color(255, 51, 0));
        manageEnterpriseJButton5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageEnterpriseJButton5.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton5.setText("return product");
        manageEnterpriseJButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButton5ActionPerformed(evt);
            }
        });

        returnJButton1.setBackground(new java.awt.Color(255, 51, 0));
        returnJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        returnJButton1.setForeground(new java.awt.Color(255, 255, 255));
        returnJButton1.setText("Return after Request");
        returnJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnJButton1ActionPerformed(evt);
            }
        });

        manageEnterpriseJButton2.setBackground(new java.awt.Color(255, 51, 0));
        manageEnterpriseJButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageEnterpriseJButton2.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton2.setText("repair");
        manageEnterpriseJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButton2ActionPerformed(evt);
            }
        });

        backjButton1.setBackground(new java.awt.Color(0, 153, 0));
        backjButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(255, 255, 255));
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageEnterpriseJButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(manageEnterpriseJButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageEnterpriseJButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageEnterpriseJButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complaintJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageEnterpriseJButton1)
                    .addComponent(returnJButton1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageEnterpriseJButton5)
                    .addComponent(manageEnterpriseJButton3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageEnterpriseJButton2)
                    .addComponent(complaintJButton2))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(274, 274, 274)
                .addComponent(backjButton1)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void complaintJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintJButton2ActionPerformed
        // TODO add your handling code here:
        ComplainRequestJPanel cjp = new ComplainRequestJPanel(userProcessContainer,user);
        userProcessContainer.add("ViewProductDetailJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_complaintJButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SupplierRequestJPanel rjp = new SupplierRequestJPanel(userProcessContainer, user, system);
        userProcessContainer.add("ManageSuppliersJPanel", rjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageEnterpriseJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButton1ActionPerformed
        // TODO add your handling code here:
        ReturnRequestJPanel rrjp = new ReturnRequestJPanel(userProcessContainer,user);
        userProcessContainer.add("manageOrganizationJPanel", rrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButton1ActionPerformed

    private void manageEnterpriseJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButton3ActionPerformed
        // TODO add your handling code here:
        ChangeRequestJPanel crjp = new ChangeRequestJPanel(userProcessContainer,user);
        userProcessContainer.add("manageOrganizationJPanel", crjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButton3ActionPerformed

    private void manageEnterpriseJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButton5ActionPerformed
        // TODO add your handling code here:
        ReturnProductRequestJPanel rpjp = new ReturnProductRequestJPanel(userProcessContainer,user);
        userProcessContainer.add("manageOrganizationJPanel", rpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButton5ActionPerformed

    private void returnJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnJButton1ActionPerformed
        // TODO add your handling code here:
        ReturnAfterRequestJPanel rrjp = new ReturnAfterRequestJPanel(userProcessContainer,user);
        userProcessContainer.add("manageOrganizationJPanel", rrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_returnJButton1ActionPerformed

    private void manageEnterpriseJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButton2ActionPerformed
        // TODO add your handling code here:
        RepairRequestJPanel rr = new RepairRequestJPanel(userProcessContainer,user);
        userProcessContainer.add("manageOrganizationJPanel", rr);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButton2ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton complaintJButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton manageEnterpriseJButton1;
    private javax.swing.JButton manageEnterpriseJButton2;
    private javax.swing.JButton manageEnterpriseJButton3;
    private javax.swing.JButton manageEnterpriseJButton5;
    private javax.swing.JButton returnJButton1;
    // End of variables declaration//GEN-END:variables
}
