/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Organization.SystemAdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.System.AmazonSystem;

/**
 *
 * @author hyf
 */
public class SystemAdminWorkareaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkareaJPanel
     */
    JPanel userProcessContainer;
    AmazonSystem system;
    SystemAdminOrganization organization;
    UserAccount account;

    public SystemAdminWorkareaJPanel(JPanel userProcessContainer, UserAccount account, SystemAdminOrganization organization, AmazonSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageNetworkJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageEnterpriseJButton1 = new javax.swing.JButton();
        manageNetworkJButton1 = new javax.swing.JButton();
        manageNetworkJButton2 = new javax.swing.JButton();
        manageNetworkJButton3 = new javax.swing.JButton();
        manageNetworkJButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageNetworkJButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        manageNetworkJButton.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton.setText("Manage Network");
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton.setBackground(new java.awt.Color(255, 51, 0));
        manageEnterpriseJButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageEnterpriseJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton1.setBackground(new java.awt.Color(255, 51, 0));
        manageEnterpriseJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageEnterpriseJButton1.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton1.setText("Enterprise Request");
        manageEnterpriseJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButton1ActionPerformed(evt);
            }
        });

        manageNetworkJButton1.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton1.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton1.setText("tax and shipping fee");
        manageNetworkJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton1ActionPerformed(evt);
            }
        });

        manageNetworkJButton2.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton2.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton2.setText("Manage Employee");
        manageNetworkJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton2ActionPerformed(evt);
            }
        });

        manageNetworkJButton3.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton3.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton3.setText("Manage organization");
        manageNetworkJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton3ActionPerformed(evt);
            }
        });

        manageNetworkJButton4.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton4.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton4.setText("Manage account");
        manageNetworkJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Work Area");

        manageNetworkJButton5.setBackground(new java.awt.Color(255, 51, 0));
        manageNetworkJButton5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        manageNetworkJButton5.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton5.setText("view tax and shipping fee");
        manageNetworkJButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(manageNetworkJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageNetworkJButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageNetworkJButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(manageNetworkJButton5))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageEnterpriseJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(manageNetworkJButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(manageNetworkJButton1))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageNetworkJButton)
                    .addComponent(manageEnterpriseJButton))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageNetworkJButton3)
                    .addComponent(manageNetworkJButton2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageNetworkJButton4)
                    .addComponent(manageEnterpriseJButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageNetworkJButton1)
                    .addComponent(manageNetworkJButton5))
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed

        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer,system);
        userProcessContainer.add("6", manageNetworkJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed

        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer,system);
        userProcessContainer.add("7", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageEnterpriseJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButton1ActionPerformed
        // TODO add your handling code here:
        EnterpriseRequestJPanel erjp = new EnterpriseRequestJPanel(userProcessContainer, organization,system);
        userProcessContainer.add("8", erjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButton1ActionPerformed

    private void manageNetworkJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton1ActionPerformed
        // TODO add your handling code here:
        ShippingAndTaxJPanel satjp = new ShippingAndTaxJPanel(userProcessContainer, organization,system);
        userProcessContainer.add("9", satjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButton1ActionPerformed

    private void manageNetworkJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton2ActionPerformed
        // TODO add your handling code here:
        ManageEmployeeJPanel satjp = new ManageEmployeeJPanel(userProcessContainer,system);
        userProcessContainer.add("0", satjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButton2ActionPerformed

    private void manageNetworkJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton3ActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel satjp = new ManageOrganizationJPanel(userProcessContainer,system);
        userProcessContainer.add("1", satjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButton3ActionPerformed

    private void manageNetworkJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton4ActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel satjp = new ManageUserAccountJPanel(userProcessContainer,system);
        userProcessContainer.add("2", satjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButton4ActionPerformed

    private void manageNetworkJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton5ActionPerformed
        // TODO add your handling code here:
        ViewShippingAndTaxJPanel satjp = new ViewShippingAndTaxJPanel(userProcessContainer, organization,system);
        userProcessContainer.add("3", satjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageEnterpriseJButton1;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JButton manageNetworkJButton1;
    private javax.swing.JButton manageNetworkJButton2;
    private javax.swing.JButton manageNetworkJButton3;
    private javax.swing.JButton manageNetworkJButton4;
    private javax.swing.JButton manageNetworkJButton5;
    // End of variables declaration//GEN-END:variables
}
